# ref https://raw.githubusercontent.com/nais/naisd/master/nais_example.yaml
image: docker.adeo.no:5000/sbl/meldekort
replicas:
  min: 1
  max: 2
  cpuThresholdPercentage: 50
port: 8080
healthcheck:
  liveness:
    path: meldekort/selftest/alive.txt
  readiness:
    path: meldekort/selftest/ready.txt
fasitResources:
  used:
  - alias: appres.cms
    resourceType: baseUrl