#'jeg vil ikke ha hjelp fra pus'
#default memory request og appdynamics feiler nå fra pus
image: docker.adeo.no:5000/arbeid/meldekort-frontend
team: meldekort
name: meldekort-frontend
replicas:
  min: 2
  max: 4
  cpuThresholdPercentage: 50
port: 8080
healthcheck:
  liveness:
    path: meldekort/selftest/alive.txt
  readiness:
    path: meldekort/selftest/ready.txt
prometheus:
  enabled: true
  path: internal/metrics
ingress:
  enabled: true
resources:
  limits:
    cpu: 3
fasitResources:
  used:
    - alias: appres.cms
      resourceType: baseUrl
