apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: {{ appName }}{{ dashEnv }}
  namespace: meldekort
  labels:
    team: meldekort
spec:
  image: {{image}}
  port: 8080
  secureLogs:
    enabled: true
  ingresses:
  {{#each ingresses as |url|}}
     - {{url}}
  {{/each}}
  liveness:
    path: /meldekort/internal/isAlive
    initialDelay: 10
  readiness:
    path: /meldekort/internal/isReady
    initialDelay: 10
  prometheus:
    enabled: true
    path: meldekort/internal/metrics
  replicas:
    min: 2
    max: 4
  webproxy: true
  resources:
    limits:
      cpu: 1000m
      memory: 512Mi
    requests:
      cpu: 300m
      memory: 512Mi
  envFrom:
    - secret: {{ appName }}{{ dashEnv }}
  env:
    - name: NAV_DEKORATOREN_URL
      value: '{{ navDekoratorenUrl }}'
    - name: DISABLE_SENSU_METRICS
      value: 'true'
  accessPolicy:
    outbound:
      rules:
        - application: meldekort-api{{ dashEnv }}
      external:
        - host: '{{ externalUrl }}'
