name: Dummy workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Miljø (støtter...)'
        required: true
        default: 'gcp'
      bump_patch:
        description: 'Skriv "bump" her for å bygge release og øke patchversjon på snapshot. Kun for main branch.'
        default: ''

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
